// Created by iWeb 3.0.4 local-build-20130320

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,338),url:'Home_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Home_files/stroke_17.png'},{rect:new IWRect(2,-2,175,4),url:'Home_files/stroke_18.png'},{rect:new IWRect(177,-2,5,4),url:'Home_files/stroke_19.png'},{rect:new IWRect(177,2,5,338),url:'Home_files/stroke_20.png'},{rect:new IWRect(177,340,5,4),url:'Home_files/stroke_21.png'},{rect:new IWRect(2,340,175,4),url:'Home_files/stroke_22.png'},{rect:new IWRect(-2,340,4,4),url:'Home_files/stroke_23.png'}],new IWSize(179,342)),reflection_0:new IWReflection({opacity:0.50,offset:1.00}),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Home_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Home_files/stroke_1.png'},{rect:new IWRect(2,-2,96,4),url:'Home_files/stroke_2.png'},{rect:new IWRect(98,-2,4,4),url:'Home_files/stroke_3.png'},{rect:new IWRect(98,2,4,96),url:'Home_files/stroke_4.png'},{rect:new IWRect(98,98,4,4),url:'Home_files/stroke_5.png'},{rect:new IWRect(2,98,96,4),url:'Home_files/stroke_6.png'},{rect:new IWRect(-2,98,4,4),url:'Home_files/stroke_7.png'}],new IWSize(100,100)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'Home_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Home_files/stroke_9.png'},{rect:new IWRect(2,-2,96,4),url:'Home_files/stroke_10.png'},{rect:new IWRect(98,-2,4,4),url:'Home_files/stroke_11.png'},{rect:new IWRect(98,2,4,96),url:'Home_files/stroke_12.png'},{rect:new IWRect(98,98,4,4),url:'Home_files/stroke_13.png'},{rect:new IWRect(2,98,96,4),url:'Home_files/stroke_14.png'},{rect:new IWRect(-2,98,4,4),url:'Home_files/stroke_15.png'}],new IWSize(100,100))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Home_files/HomeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
